name: Manual Release

on:
  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Get Date
        uses: Kaven-Universe/github-action-current-date-time@v1
        id: current-time
        with:
          format: "YYYYMMDD"
    outputs:
      RELEASE_DATE: ${{ steps.current-time.outputs.time }}
      FILE_NAME: cocosx_release_${{ steps.current-time.outputs.time }}.zip
  release:
    runs-on: ubuntu-latest
    needs: pre
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Packing Project
        id: packing-project
        env:
          FILE_NAME: ${{ needs.pre.outputs.FILE_NAME }}
        run: |
          echo FILE_NAME: $FILE_NAME
          zip -q -1 -r $FILE_NAME *
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_DATE: ${{ needs.pre.outputs.RELEASE_DATE }}
        with:
          files: |
            *.zip
          token: ${{ env.GITHUB_TOKEN }}
          name: ${{ env.RELEASE_DATE }}
          tag_name: ${{ env.RELEASE_DATE }}
          body: |
            Release ${{ env.RELEASE_DATE }}
          append_body: true
          generate_release_notes: true
          draft: false
          prerelease: false